# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ic_llk <- function(x, betas, weight) {
    .Call('InvCon_ic_llk', PACKAGE = 'InvCon', x, betas, weight)
}

ic_mass <- function(x, betas) {
    .Call('InvCon_ic_mass', PACKAGE = 'InvCon', x, betas)
}

move_active <- function(ind, h, act_inds, x, betas) {
    invisible(.Call('InvCon_move_active', PACKAGE = 'InvCon', ind, h, act_inds, x, betas))
}

ic_act_ders <- function(ind, d_vec, act_inds, x, betas, weight, h = 0.0001) {
    invisible(.Call('InvCon_ic_act_ders', PACKAGE = 'InvCon', ind, d_vec, act_inds, x, betas, weight, h))
}

ic_active <- function(active, x, betas, slack = 0.00000001) {
    invisible(.Call('InvCon_ic_active', PACKAGE = 'InvCon', active, x, betas, slack))
}

ic_aerr_vec <- function(e_vec, act_inds, x, betas, weight) {
    invisible(.Call('InvCon_ic_aerr_vec', PACKAGE = 'InvCon', e_vec, act_inds, x, betas, weight))
}

act_d_vec <- function(x, d_vec, act_inds, a_d_vec) {
    invisible(.Call('InvCon_act_d_vec', PACKAGE = 'InvCon', x, d_vec, act_inds, a_d_vec))
}

p_ic <- function(x, fit_x, fit_dens) {
    .Call('InvCon_p_ic', PACKAGE = 'InvCon', x, fit_x, fit_dens)
}

d_ic <- function(x, fit_x, fit_dens) {
    .Call('InvCon_d_ic', PACKAGE = 'InvCon', x, fit_x, fit_dens)
}

rcpp_hello_world <- function() {
    .Call('InvCon_rcpp_hello_world', PACKAGE = 'InvCon')
}

