# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_yw <- function(Y_mat, Omega, r, w) {
    .Call(`_monoMissGMM_sum_yw`, Y_mat, Omega, r, w)
}

compute_y_r <- function(data, Omega, w) {
    .Call(`_monoMissGMM_compute_y_r`, data, Omega, w)
}

chol_lowRankUpdate <- function(xs, Ld, ws, update) {
    .Call(`_monoMissGMM_chol_lowRankUpdate`, xs, Ld, ws, update)
}

add_weighted_outer_prod <- function(v, m, w) {
    invisible(.Call(`_monoMissGMM_add_weighted_outer_prod`, v, m, w))
}

computeMLE_with_yr <- function(data, ws, Omega, y_r, ss_start) {
    .Call(`_monoMissGMM_computeMLE_with_yr`, data, ws, Omega, y_r, ss_start)
}

computeMLE <- function(data, ws, Omega, ss_start) {
    .Call(`_monoMissGMM_computeMLE`, data, ws, Omega, ss_start)
}

forwardSolve <- function(low_chol, y, r) {
    .Call(`_monoMissGMM_forwardSolve`, low_chol, y, r)
}

dmvnorm_Omega <- function(data, mu, chol_S, Omega) {
    .Call(`_monoMissGMM_dmvnorm_Omega`, data, mu, chol_S, Omega)
}

dmvnorm_one <- function(x, mu, chol_S, r) {
    .Call(`_monoMissGMM_dmvnorm_one`, x, mu, chol_S, r)
}

dmvnorm_mono <- function(x, mu, chol_S, r) {
    .Call(`_monoMissGMM_dmvnorm_mono`, x, mu, chol_S, r)
}

