// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ic_llk
double ic_llk(NumericVector x, NumericVector betas, NumericVector weight);
RcppExport SEXP InvCon_ic_llk(SEXP xSEXP, SEXP betasSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type betas(betasSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP );
        double __result = ic_llk(x, betas, weight);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// ic_mass
double ic_mass(NumericVector x, NumericVector betas);
RcppExport SEXP InvCon_ic_mass(SEXP xSEXP, SEXP betasSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type betas(betasSEXP );
        double __result = ic_mass(x, betas);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// move_active
void move_active(int ind, double h, IntegerVector act_inds, NumericVector x, NumericVector betas);
RcppExport SEXP InvCon_move_active(SEXP indSEXP, SEXP hSEXP, SEXP act_indsSEXP, SEXP xSEXP, SEXP betasSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type ind(indSEXP );
        Rcpp::traits::input_parameter< double >::type h(hSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type act_inds(act_indsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type betas(betasSEXP );
        move_active(ind, h, act_inds, x, betas);
    }
    return R_NilValue;
END_RCPP
}
// ic_act_ders
void ic_act_ders(int ind, NumericVector d_vec, IntegerVector act_inds, NumericVector x, NumericVector betas, NumericVector weight, double h = 0.0001);
RcppExport SEXP InvCon_ic_act_ders(SEXP indSEXP, SEXP d_vecSEXP, SEXP act_indsSEXP, SEXP xSEXP, SEXP betasSEXP, SEXP weightSEXP, SEXP hSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type ind(indSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type d_vec(d_vecSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type act_inds(act_indsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type betas(betasSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP );
        Rcpp::traits::input_parameter< double >::type h(hSEXP );
        ic_act_ders(ind, d_vec, act_inds, x, betas, weight, h);
    }
    return R_NilValue;
END_RCPP
}
// ic_active
void ic_active(LogicalVector active, NumericVector x, NumericVector betas, double slack = 0.00000001);
RcppExport SEXP InvCon_ic_active(SEXP activeSEXP, SEXP xSEXP, SEXP betasSEXP, SEXP slackSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< LogicalVector >::type active(activeSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type betas(betasSEXP );
        Rcpp::traits::input_parameter< double >::type slack(slackSEXP );
        ic_active(active, x, betas, slack);
    }
    return R_NilValue;
END_RCPP
}
// ic_aerr_vec
void ic_aerr_vec(NumericVector e_vec, IntegerVector act_inds, NumericVector x, NumericVector betas, NumericVector weight);
RcppExport SEXP InvCon_ic_aerr_vec(SEXP e_vecSEXP, SEXP act_indsSEXP, SEXP xSEXP, SEXP betasSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type e_vec(e_vecSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type act_inds(act_indsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type betas(betasSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP );
        ic_aerr_vec(e_vec, act_inds, x, betas, weight);
    }
    return R_NilValue;
END_RCPP
}
// act_d_vec
void act_d_vec(NumericVector x, NumericVector d_vec, IntegerVector act_inds, NumericVector a_d_vec);
RcppExport SEXP InvCon_act_d_vec(SEXP xSEXP, SEXP d_vecSEXP, SEXP act_indsSEXP, SEXP a_d_vecSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type d_vec(d_vecSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type act_inds(act_indsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type a_d_vec(a_d_vecSEXP );
        act_d_vec(x, d_vec, act_inds, a_d_vec);
    }
    return R_NilValue;
END_RCPP
}
// p_ic
double p_ic(double x, NumericVector fit_x, NumericVector fit_dens);
RcppExport SEXP InvCon_p_ic(SEXP xSEXP, SEXP fit_xSEXP, SEXP fit_densSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type fit_x(fit_xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type fit_dens(fit_densSEXP );
        double __result = p_ic(x, fit_x, fit_dens);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// d_ic
double d_ic(double x, NumericVector fit_x, NumericVector fit_dens);
RcppExport SEXP InvCon_d_ic(SEXP xSEXP, SEXP fit_xSEXP, SEXP fit_densSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type fit_x(fit_xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type fit_dens(fit_densSEXP );
        double __result = d_ic(x, fit_x, fit_dens);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP InvCon_rcpp_hello_world() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcpp_hello_world();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
