# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_nonLinearEmbed_rcpp_hello_world', PACKAGE = 'nonLinearEmbed')
}

estLLK <- function(is, js, hasEdges, ws, coord, etas) {
    .Call('_nonLinearEmbed_estLLK', PACKAGE = 'nonLinearEmbed', is, js, hasEdges, ws, coord, etas)
}

sgd_updates <- function(is, js, hasEdges, ws, alphas, coord, etas, h) {
    .Call('_nonLinearEmbed_sgd_updates', PACKAGE = 'nonLinearEmbed', is, js, hasEdges, ws, alphas, coord, etas, h)
}

